# .travis.yml

language: "java"

sudo: false

jdk:
  - "oraclejdk9"

addons:
  apt:
    packages:
      - "oracle-java8-installer"
      - "ant-optional"

script:
  - "ant -f pmd85/build.xml test && ant -f ondra/build.xml test"
