build:
	$(MAKE) -C reversi build
	$(MAKE) -C sudoku build
	$(MAKE) -C logik build
	$(MAKE) -C sokoban build

clean:
	$(MAKE) -C reversi clean
	$(MAKE) -C sudoku clean
	$(MAKE) -C logik clean
	$(MAKE) -C sokoban clean

.PHONY: build clean
