build:
	$(MAKE) -C lib build
	$(MAKE) -C reversi build
	$(MAKE) -C sudoku build
	$(MAKE) -C logik build
	$(MAKE) -C sokoban build
	$(MAKE) -C forth build

clean:
	$(MAKE) -C lib clean
	$(MAKE) -C reversi clean
	$(MAKE) -C sudoku clean
	$(MAKE) -C logik clean
	$(MAKE) -C sokoban clean
	$(MAKE) -C forth clean

.PHONY: build clean
